### ISSUE TITLE
Does not display any buttons on steam pages when enabled

### ISSUE THREAD

**Issue by ReagentX** [metjm/SteamWizard#4]
For some reason #3 was closed however the issue is not resolved.

**Comment by metjm** [comment]
Can you give more information? Are there specific items where it happens? if so which ones? do you have any other csgo related extensions? does it always happen with a certain item or only sometimes? 
Also extension version number and chrome version
Thanks

**Comment by ReagentX** [comment]
Here is another link where the extension does not work:

https://steamcommunity.com/market/listings/730/XM1014%20%7C%20Tranquility%20%28Factory%20New
%29

Seems to be related to using the radio buttons to adjust how many get displayed in the list.

**Comment by metjm** [comment]
I'm unable to replicate the issue. Do you have any other extensions running that remove/replace the itemlist?
